"use client";

import { useEffect, useRef } from "react";

const CLIPS = [
  "hf_20260614_231258_3288b082-d129-4358-b1cb-3483361ce6bf.mp4",
  "hf_20260615_013951_d38987be-50f4-4fd8-a070-e2537b2d3c9a.mp4",
  "hf_20260615_021248_74a5177c-0fec-4b2d-b440-d4ec1855089c.mp4",
  "hf_20260615_225317_b48e0bba-4995-4516-84a6-50ebb3d972a8.mp4",
  "hf_20260615_235620_4bf5ef7e-46f2-48c2-bb68-db1bf39f38ef.mp4",
  "hf_20260616_205611_e9059dab-3079-4920-81fe-cbaf7062dd6a.mp4",
  "hf_20260616_211244_e8668434-14ae-41be-8a46-92a921c7736c.mp4",
  "hf_20260616_213304_7f1c29cc-f668-4d7c-ace3-f4fba1a6480d.mp4",
  "hf_20260617_222752_31b8c67c-58c4-40f2-9d6c-5c54b0c5e2a2.mp4",
  "hf_20260618_011147_3cf1fbd4-6e55-40ca-9ca0-a7a96ef16a19.mp4",
  "hf_20260623_001711_b1cfd9e9-ea89-42af-8967-3885707dd5b9.mp4",
];

export function ReferenceReel({
  eyebrow = "DAILIES — SHOT ON REELFORM",
  title = "Footage our users put on their sites",
  subtitle = "Every clip below was directed with a plain-language prompt and generated by Seedance — the same footage that ends up looping or scrubbing behind a hero section.",
  action,
}: {
  eyebrow?: string;
  title?: string;
  subtitle?: string;
  action?: React.ReactNode;
}) {
  const stripRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const strip = stripRef.current;
    if (!strip) return;
    const videos = Array.from(strip.querySelectorAll<HTMLVideoElement>("video[data-src]"));

    const observer = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          const video = entry.target as HTMLVideoElement;
          if (entry.isIntersecting) {
            if (!video.src) video.src = video.dataset.src!;
            video.play().catch(() => {});
          } else {
            video.pause();
          }
        }
      },
      { rootMargin: "200px" }
    );

    videos.forEach((v) => observer.observe(v));
    return () => observer.disconnect();
  }, []);

  const scrollBy = (dir: number) => {
    const strip = stripRef.current;
    if (!strip) return;
    strip.scrollBy({ left: dir * strip.clientWidth * 0.8, behavior: "smooth" });
  };

  return (
    <section className="bg-ink text-white py-24 overflow-hidden">
      <div className="px-6 md:px-10 max-w-6xl mx-auto flex items-end justify-between gap-6">
        <div>
          <p className="mono-label !text-white/60">{eyebrow}</p>
          <h2 className="mt-3 text-3xl md:text-4xl font-medium tracking-tight">{title}</h2>
          <p className="mt-3 text-white/70 max-w-xl leading-relaxed">{subtitle}</p>
          {action && <div className="mt-5">{action}</div>}
        </div>
        <div className="hidden md:flex gap-2 shrink-0">
          <button
            type="button"
            onClick={() => scrollBy(-1)}
            aria-label="Scroll to previous clips"
            className="w-11 h-11 rounded-full border border-white/30 text-white/80 hover:border-white hover:text-white transition-colors"
          >
            ←
          </button>
          <button
            type="button"
            onClick={() => scrollBy(1)}
            aria-label="Scroll to next clips"
            className="w-11 h-11 rounded-full border border-white/30 text-white/80 hover:border-white hover:text-white transition-colors"
          >
            →
          </button>
        </div>
      </div>

      <div
        ref={stripRef}
        className="reel-strip mt-10 flex gap-4 overflow-x-auto px-6 md:px-[max(2.5rem,calc((100vw-72rem)/2+2.5rem))] pb-2"
      >
        {CLIPS.map((file, i) => (
          <figure
            key={file}
            className="relative shrink-0 w-[80vw] sm:w-[24rem] snap-start rounded-xl overflow-hidden border border-white/10 bg-white/5"
          >
            <video
              data-src={`/ReferenceVids/${file}`}
              muted
              loop
              playsInline
              preload="none"
              className="aspect-video w-full object-cover"
            />
            <figcaption className="absolute top-3 left-3 flex items-center gap-2 bg-ink/70 backdrop-blur-sm rounded px-2.5 py-1">
              <span className="rec-dot !w-2 !h-2" aria-hidden />
              <span className="text-[0.65rem] font-bold tracking-[0.15em] text-white/80">
                TAKE {String(i + 1).padStart(2, "0")}
              </span>
            </figcaption>
          </figure>
        ))}
      </div>

      <p className="mt-6 px-6 md:px-10 max-w-6xl mx-auto text-xs text-white/40">
        Clips stream in as you scroll — nothing loads until it's on screen.
      </p>
    </section>
  );
}
